# Sharnouby Analysis Project

---
### Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import os
from pathlib import Path
%matplotlib inline


pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

---
### Loading & Inspecting Datasets

In [2]:
files = {
    "business_units":    "Business_Units.csv",
    "case_briefs":       "Case_Briefs.csv",
    "customer_service":  "Customer_Service.csv",
    "customers":         "Customers.csv",
    "data_dictionary":   "Data_Dictionary.csv",
    "group_operations":  "Group_Operations.csv",
    "inventory_history": "Inventory_History.csv",
    "locations":         "Locations.csv",
    "machine_downtime":  "Machine_Downtime.csv",
    "marketing":         "Marketing.csv",
    "materials":         "Materials.csv",
    "printing_batches":  "Printing_Batches.csv",
    "product_bom":       "Product_BOM.csv",
    "product_master":    "Product_Master.csv",
    "production_orders": "Production_Orders.csv",
    "purchase_orders":   "Purchase_Orders.csv",
    "quality":           "Quality.csv",
    "sales_transactions":"Sales_Transactions.csv",
    "suppliers":         "Suppliers.csv",
    "web_traffic_daily": "Web_Traffic_Daily.csv",
}


dfs = {name: pd.read_csv(fname) for name, fname in files.items()}


for name, df in dfs.items():
    print(f"{name:22s} shape={df.shape}")

business_units         shape=(5, 5)
case_briefs            shape=(10, 4)
customer_service       shape=(6500, 9)
customers              shape=(30000, 9)
data_dictionary        shape=(19, 4)
group_operations       shape=(180, 7)
inventory_history      shape=(6372, 19)
locations              shape=(5, 9)
machine_downtime       shape=(2800, 8)
marketing              shape=(420, 15)
materials              shape=(12, 6)
printing_batches       shape=(1900, 15)
product_bom            shape=(337, 7)
product_master         shape=(59, 12)
production_orders      shape=(2500, 16)
purchase_orders        shape=(3600, 13)
quality                shape=(9000, 12)
sales_transactions     shape=(180000, 30)
suppliers              shape=(12, 7)
web_traffic_daily      shape=(1096, 11)

In [3]:
for name, df in dfs.items():
    print("="*70)
    print(name.upper())
    print(df.dtypes)
    print("Missing values:")
    print(df.isna().sum()[df.isna().sum() > 0])
    display(df.head(3))

======================================================================
BUSINESS_UNITS
Business_Unit         object
Function              object
Public_Capacity       object
Source_URL            object
Verification_Class    object
dtype: object
Missing values:
Series([], dtype: int64)

        Business_Unit                                          Function                                    Public_Capacity                             Source_URL   Verification_Class
0          LEO DESIGN  Fashion design, pattern making, 3D visualization                                Not publicly stated          https://www.el-sharnouby.com/  Public company fact
1             LEO TEX                        Woven fabric manufacturing  Integrated textile manufacturing; exact capaci...  https://www.el-sharnouby.com/services  Public company fact
2  LEO PRODUCTION HUB                             Garment manufacturing                             Up to 5,000 pieces/day  https://www.el-sharnouby.com/services  Public company fact

======================================================================
CASE_BRIEFS
Card_No                  int64
Title                   object
Business_Problem        object
Expected_Deliverable    object
dtype: object
Missing values:
Series([], dtype: int64)

   Card_No                            Title                                   Business_Problem                               Expected_Deliverable
0        1  Executive Sales & Profitability  Revenue is growing, but management is unsure w...  Build an executive view of revenue, units, gro...
1        2         Customer 360 & Retention  The business has a growing customer base, but ...  Create customer segments using RFM/cohorts, re...
2        3     Branch & Channel Performance  Retail, online and wholesale operate different...  Compare channel growth, margin, returns, baske...

======================================================================
CUSTOMER_SERVICE
Ticket_ID                  object
Open_Date                  object
Channel                    object
Issue_Type                 object
First_Response_Minutes    float64
Resolution_Hours          float64
Resolved                   object
CSAT_1_to_5                 int64
Data_Class                 object
dtype: object
Missing values:
Series([], dtype: int64)

  Ticket_ID   Open_Date    Channel       Issue_Type  First_Response_Minutes  Resolution_Hours Resolved  CSAT_1_to_5                            Data_Class
0  TKT00001  2025-02-02   WhatsApp   Return request                     6.5               9.3      Yes            2  Modeled customer service interaction
1  TKT00002  2024-01-01  Instagram     Order status                    21.8              10.1      Yes            4  Modeled customer service interaction
2  TKT00003  2026-03-21   WhatsApp  Product quality                     7.0               7.7      Yes            5  Modeled customer service interaction

======================================================================
CUSTOMERS
Customer_ID            object
Customer_Type          object
Governorate            object
Age_Band               object
Gender                 object
Join_Date              object
Acquisition_Channel    object
Consent_Status         object
Data_Class             object
dtype: object
Missing values:
Series([], dtype: int64)

  Customer_ID Customer_Type Governorate Age_Band  Gender   Join_Date Acquisition_Channel Consent_Status                                         Data_Class
0      C00001        Retail    Dakahlia    45-54    Male  2026-02-22      Organic Social   Not opted-in  Modeled/anonymized training customer - not act...
1      C00002        Retail     Beheira    35-44    Male  2024-09-30   Direct / WhatsApp       Opted-in  Modeled/anonymized training customer - not act...
2      C00003        Retail    Dakahlia    25-34  Female  2025-06-27      Organic Social       Opted-in  Modeled/anonymized training customer - not act...

======================================================================
DATA_DICTIONARY
Table              object
Grain              object
Purpose            object
Real_vs_Modeled    object
dtype: object
Missing values:
Series([], dtype: int64)

                Table                                   Grain                                            Purpose                                    Real_vs_Modeled
0  Product_Master.csv                1 row per public product  Public product catalog master and public retai...                        Public/verified master data
1  Business_Units.csv         1 row per company business unit          Group structure and public capacity facts                              Public/verified facts
2       Locations.csv  1 row per channel / operating location  Retail, online, wholesale, HQ and factory context  Public facts where available; exact factory ad...

======================================================================
GROUP_OPERATIONS
Month                          object
Business_Unit                  object
Primary_KPI                    object
Volume                          int64
Operational_Efficiency_Pct    float64
Open_Issues_Count               int64
Data_Class                     object
dtype: object
Missing values:
Series([], dtype: int64)

        Month       Business_Unit        Primary_KPI  Volume  Operational_Efficiency_Pct  Open_Issues_Count                                         Data_Class
0  2023-10-01          LEO DESIGN  Designs_Completed      48                        85.1                  2  Modeled monthly operational summary using publ...
1  2023-10-01             LEO TEX      Fabric_Meters  129278                        91.5                  6  Modeled monthly operational summary using publ...
2  2023-10-01  LEO PRODUCTION HUB  Garments_Produced   78490                        88.5                  9  Modeled monthly operational summary using publ...

======================================================================
INVENTORY_HISTORY
Snapshot_Month              object
Location_ID                 object
Location_Name               object
Product_ID                  object
SKU                         object
Product_Name                object
Opening_Stock                int64
Received_Qty                 int64
Sold_Qty                     int64
Returned_Qty                 int64
Damaged_Qty                  int64
Closing_Stock                int64
Avg_Daily_Sales_90D        float64
Safety_Stock_Units           int64
Reorder_Point_Units          int64
Supplier_Lead_Time_Days      int64
Days_of_Cover              float64
Stockout_Days_In_Month       int64
Data_Class                  object
dtype: object
Missing values:
Series([], dtype: int64)

,Snapshot_Month,Location_ID,Location_Name,Product_ID,SKU,Product_Name,Opening_Stock,Received_Qty,Sold_Qty,Returned_Qty,Damaged_Qty,Closing_Stock,Avg_Daily_Sales_90D,Safety_Stock_Units,Reorder_Point_Units,Supplier_Lead_Time_Days,Days_of_Cover,Stockout_Days_In_Month,Data_Class
0,2023-10-01,LOC001,LEO MODA - Sidi Bishr Store,P001,26115-8,Summer children's girls-Happy,176,39,42,3,0,176,1.38,5,12,5,127.5,0,Modeled inventory history - no forecast column...
1,2023-11-01,LOC001,LEO MODA - Sidi Bishr Store,P001,26115-8,Summer children's girls-Happy,176,65,62,4,1,182,1.71,23,59,21,106.4,0,Modeled inventory history - no forecast column...
2,2023-12-01,LOC001,LEO MODA - Sidi Bishr Store,P001,26115-8,Summer children's girls-Happy,182,54,61,1,1,175,1.81,25,63,21,96.7,0,Modeled inventory history - no forecast column...

======================================================================
LOCATIONS
Location_ID           object
Location_Name         object
Location_Type         object
Channel               object
Governorate           object
City                  object
Public_Address        object
Source_URL            object
Verification_Class    object
dtype: object
Missing values:
Series([], dtype: int64)

,Location_ID,Location_Name,Location_Type,Channel,Governorate,City,Public_Address,Source_URL,Verification_Class
0,LOC001,LEO MODA - Sidi Bishr Store,Retail Store,Retail,Alexandria,Sidi Bishr,"72C2+GXJ, Sidi Bishr Bahri, Montaza 2, Alexand...",https://leo.moda/our-stores/,Public store / address cross-checked from publ...
1,LOC002,LEO MODA Online Store,Digital Store,Online,Egypt,Nationwide,Online - delivery across Egypt,https://leo.moda/,Public channel
2,LOC003,El-Sharnouby Wholesale Desk,B2B / Wholesale,Wholesale,Alexandria,Zizinia,"5 Amin Yehia Street, Zizinia, Alexandria, Egypt",https://www.el-sharnouby.com/,Public HQ / wholesale inquiry channel

======================================================================
MACHINE_DOWNTIME
Downtime_ID        object
Date               object
Machine_ID         object
Business_Area      object
Downtime_Hours    float64
Reason             object
Planned            object
Data_Class         object
dtype: object
Missing values:
Series([], dtype: int64)

  Downtime_ID        Date Machine_ID Business_Area  Downtime_Hours               Reason Planned               Data_Class
0     DT00001  2025-05-21     CUT-01       Cutting             0.7  Planned maintenance     Yes  Modeled equipment event
1     DT00002  2026-02-14     PR-M03      Printing             0.8   Setup / changeover      No  Modeled equipment event
2     DT00003  2024-04-11     PR-M04      Printing            11.7   Setup / changeover      No  Modeled equipment event

======================================================================
MARKETING
Campaign_ID                object
Campaign_Name              object
Product_ID                 object
Product_Name               object
Platform                   object
Start_Date                 object
End_Date                   object
Spend_EGP                   int64
Impressions                 int64
Clicks                      int64
Landing_Page_Sessions       int64
Orders_Attributed           int64
Attributed_Revenue_EGP    float64
Discount_Pct              float64
Data_Class                 object
dtype: object
Missing values:
Series([], dtype: int64)

,Campaign_ID,Campaign_Name,Product_ID,Product_Name,Platform,Start_Date,End_Date,Spend_EGP,Impressions,Clicks,Landing_Page_Sessions,Orders_Attributed,Attributed_Revenue_EGP,Discount_Pct,Data_Class
0,CMP0001,Meta | Boys' summer pajamas-Wear your a | May24,P018,Boys' summer pajamas-Wear your attitude,Meta,2024-05-24,2024-06-08,24313,549466,6835,6835,103,41337.81,0.15,Modeled campaign performance - not actual medi...
1,CMP0002,TikTok | Girls' pajamas-Daylife+kuromi | Dec24,P029,Girls' pajamas-Daylife+kuromi,TikTok,2024-12-24,2024-12-29,25303,626807,13393,13393,193,95701.65,0.10,Modeled campaign performance - not actual medi...
2,CMP0003,Google | Boys' Autumn Pajamas-Loony Tunes | Oct25,P040,Boys' Autumn Pajamas-Loony Tunes,Google,2025-10-22,2025-11-13,47808,542947,17336,17336,881,353823.52,0.00,Modeled campaign performance - not actual medi...

======================================================================
MATERIALS
Material_ID                object
Material_Name              object
Unit                       object
Material_Category          object
Standard_Lead_Time_Days     int64
Data_Class                 object
dtype: object
Missing values:
Series([], dtype: int64)

  Material_ID                 Material_Name   Unit Material_Category  Standard_Lead_Time_Days                           Data_Class
0        M001  Single Jersey Cotton 160 GSM  meter            Fabric                       10  Modeled operational material master
1        M002  Single Jersey Cotton 180 GSM  meter            Fabric                       14  Modeled operational material master
2        M003                    Rib Cotton  meter            Fabric                       10  Modeled operational material master

======================================================================
PRINTING_BATCHES
Print_Batch_ID                 object
Product_ID                     object
Product_Name                   object
Print_Date                     object
Print_Type                     object
Machine_ID                     object
Planned_Qty                     int64
Printed_Qty                     int64
Good_Qty                        int64
Rejected_Qty                    int64
Reprint_Qty                     int64
Defect_Type                    object
Ink_or_Consumable_Cost_EGP    float64
Rework_Cost_EGP               float64
Data_Class                     object
dtype: object
Missing values:
Defect_Type    381
dtype: int64

,Print_Batch_ID,Product_ID,Product_Name,Print_Date,Print_Type,Machine_ID,Planned_Qty,Printed_Qty,Good_Qty,Rejected_Qty,Reprint_Qty,Defect_Type,Ink_or_Consumable_Cost_EGP,Rework_Cost_EGP,Data_Class
0,PR00001,P015,Girls' summer pajamas-Stay cool,2023-10-29,Digital,PR-M02,3240,3119,3055,64,31,NaN,12570.15,178.57,Modeled print operation
1,PR00002,P051,Ice cream - بيجامة حريمي صيفي2024,2025-05-13,Water-Based,PR-M02,949,926,882,44,31,Curing,6152.74,244.02,Modeled print operation
2,PR00003,P015,Girls' summer pajamas-Stay cool,2025-07-20,Heat Transfer,PR-M05,5242,5185,5007,178,81,Curing,24019.22,375.21,Modeled print operation

======================================================================
PRODUCT_BOM
Product_ID            object
Product_Name          object
Material_ID           object
Material_Name         object
Required_Per_Unit    float64
Unit                  object
Data_Class            object
dtype: object
Missing values:
Series([], dtype: int64)

  Product_ID                   Product_Name Material_ID                 Material_Name  Required_Per_Unit   Unit                Data_Class
0       P001  Summer children's girls-Happy        M001  Single Jersey Cotton 160 GSM              1.040  meter  Modeled BOM for training
1       P001  Summer children's girls-Happy        M006                 Sewing Thread              0.032   cone  Modeled BOM for training
2       P001  Summer children's girls-Happy        M007                    Neck Label              1.000  piece  Modeled BOM for training

======================================================================
PRODUCT_MASTER
Product_ID                 object
SKU                        object
Product_Name               object
Brand                      object
Product_Family             object
Gender                     object
Audience                   object
Catalog_Season             object
Sizes                      object
Public_Retail_Price_EGP     int64
Public_Catalog_Source      object
Verification_Class         object
dtype: object
Missing values:
Series([], dtype: int64)

,Product_ID,SKU,Product_Name,Brand,Product_Family,Gender,Audience,Catalog_Season,Sizes,Public_Retail_Price_EGP,Public_Catalog_Source,Verification_Class
0,P001,26115-8,Summer children's girls-Happy,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",348,https://leo.moda/shop/,Public catalog product / public retail price
1,P002,26115-6,Summer children's girls-turtle,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",348,https://leo.moda/shop/,Public catalog product / public retail price
2,P003,26115-5,Summer children's girls-Hello kitty Rose & tur...,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",348,https://leo.moda/shop/,Public catalog product / public retail price

======================================================================
PRODUCTION_ORDERS
Production_Order_ID     object
Product_ID              object
Product_Name            object
Start_Date              object
Due_Date                object
Completion_Date         object
Planned_Qty              int64
Produced_Qty             int64
Good_Qty                 int64
Rejected_Qty             int64
Line_ID                 object
Efficiency_Pct         float64
Delay_Days               int64
Primary_Bottleneck      object
Overtime_Hours         float64
Data_Class              object
dtype: object
Missing values:
Primary_Bottleneck    2093
dtype: int64

,Production_Order_ID,Product_ID,Product_Name,Start_Date,Due_Date,Completion_Date,Planned_Qty,Produced_Qty,Good_Qty,Rejected_Qty,Line_ID,Efficiency_Pct,Delay_Days,Primary_Bottleneck,Overtime_Hours,Data_Class
0,PO00001,P035,Girls' sweatshirt-Fuchsia,2025-11-11,2025-11-22,2025-11-22,1228,1140,1124,16,LINE-05,81.1,0,NaN,4.5,Modeled factory production order
1,PO00002,P055,Scooby-Doo - بيجامة حريمي صيفي2024,2025-09-01,2025-09-19,2025-09-19,1215,1215,1185,30,LINE-04,89.7,0,NaN,0.5,Modeled factory production order
2,PO00003,P001,Summer children's girls-Happy,2025-03-22,2025-04-08,2025-04-15,613,580,562,18,LINE-04,86.5,7,Finishing,14.7,Modeled factory production order

======================================================================
PURCHASE_ORDERS
PO_ID                   object
Order_Date              object
Supplier_ID             object
Material_ID             object
Material_Name           object
Unit                    object
Ordered_Qty              int64
Unit_Cost_EGP          float64
Promised_Date           object
Actual_Receipt_Date     object
Accepted_Qty             int64
Rejected_Qty             int64
Data_Class              object
dtype: object
Missing values:
Series([], dtype: int64)

,PO_ID,Order_Date,Supplier_ID,Material_ID,Material_Name,Unit,Ordered_Qty,Unit_Cost_EGP,Promised_Date,Actual_Receipt_Date,Accepted_Qty,Rejected_Qty,Data_Class
0,MPO00001,2025-02-02,SUP04,M010,Carton Box,piece,3880,8.07,2025-02-16,2025-02-21,3777,103,Modeled procurement / supplier performance
1,MPO00002,2025-10-18,SUP07,M001,Single Jersey Cotton 160 GSM,meter,1332,85.55,2025-10-23,2025-10-23,1309,23,Modeled procurement / supplier performance
2,MPO00003,2024-02-17,SUP04,M012,Heat Transfer Film,sheet,13868,10.79,2024-02-24,2024-02-24,13582,286,Modeled procurement / supplier performance

======================================================================
QUALITY
QC_ID                  object
Inspection_Date        object
Product_ID             object
Product_Name           object
Stage                  object
Inspected_Qty           int64
Passed_Qty              int64
Rejected_Qty            int64
Defect_Type            object
Root_Cause             object
Estimated_Loss_EGP    float64
Data_Class             object
dtype: object
Missing values:
Defect_Type    1972
dtype: int64

,QC_ID,Inspection_Date,Product_ID,Product_Name,Stage,Inspected_Qty,Passed_Qty,Rejected_Qty,Defect_Type,Root_Cause,Estimated_Loss_EGP,Data_Class
0,QC000001,2026-03-09,P049,Fuchsia - طقم تيشيرت وشورت اطفال صيفي,Fabric,40,39,1,NaN,No significant issue,239.99,Modeled QC inspection
1,QC000002,2025-09-21,P027,Girls' pajamas - I'm Just a girl,Finishing,629,613,16,Color Misalignment,Operator method,1689.62,Modeled QC inspection
2,QC000003,2024-08-21,P008,Summer children's boys-SpongeBob,Finishing,577,553,24,Print Cracking,No significant issue,4343.01,Modeled QC inspection

======================================================================
SALES_TRANSACTIONS
Row_ID                      int64
Invoice_ID                 object
Order_Date                 object
Month_Key                  object
Location_ID                object
Location_Name              object
Channel                    object
Customer_ID                object
Customer_Type              object
Customer_Governorate       object
Product_ID                 object
SKU                        object
Product_Name               object
Product_Family             object
Size                       object
Quantity                    int64
List_Price_EGP              int64
Discount_Pct              float64
Gross_Sales_EGP             int64
Net_Sales_EGP             float64
Estimated_COGS_EGP        float64
Gross_Profit_EGP          float64
Gross_Margin_Pct          float64
Payment_Method             object
Returned                   object
Return_Date                object
Return_Reason              object
Refund_Value_EGP          float64
Quality_Related_Return     object
Data_Class                 object
dtype: object
Missing values:
Return_Date    171457
dtype: int64

,Row_ID,Invoice_ID,Order_Date,Month_Key,Location_ID,Location_Name,Channel,Customer_ID,Customer_Type,Customer_Governorate,Product_ID,SKU,Product_Name,Product_Family,Size,Quantity,List_Price_EGP,Discount_Pct,Gross_Sales_EGP,Net_Sales_EGP,Estimated_COGS_EGP,Gross_Profit_EGP,Gross_Margin_Pct,Payment_Method,Returned,Return_Date,Return_Reason,Refund_Value_EGP,Quality_Related_Return,Data_Class
0,0,INV0000001,2024-05-11,2024-05,LOC002,LEO MODA Online Store,Online,C18976,Retail,Cairo,P059,CAT-059,Positive vibes - 2024بيجامة حريمي صيفي,Pajamas/Homewear,M,1,388,0.15,388,329.8,247.57,82.23,0.2493,Wallet,No,NaN,No return,0.0,No,Modeled training transaction anchored to publi...
1,1,INV0000002,2025-07-31,2025-07,LOC001,LEO MODA - Sidi Bishr Store,Retail,C22543,Retail,Alexandria,P038,CAT-038,Boys' Autumn Pajamas-Mickey Mouse,Pajamas/Homewear,8,1,289,0.20,289,231.2,163.31,67.89,0.2936,Card,No,NaN,No return,0.0,No,Modeled training transaction anchored to publi...
2,2,INV0000003,2026-05-23,2026-05,LOC003,El-Sharnouby Wholesale Desk,Wholesale,C13351,Wholesale,Alexandria,P028,CAT-028,Girls' summer pajamas,Pajamas/Homewear,6,24,295,0.32,7080,4814.4,4301.71,512.69,0.1065,Cash,No,NaN,No return,0.0,No,Modeled training transaction anchored to publi...

======================================================================
SUPPLIERS
Supplier_ID           object
Supplier_Name         object
Primary_Category      object
Governorate           object
Payment_Terms_Days     int64
Contracted            object
Data_Class            object
dtype: object
Missing values:
Series([], dtype: int64)

  Supplier_ID                      Supplier_Name Primary_Category Governorate  Payment_Terms_Days Contracted                                         Data_Class
0       SUP01  Approved Supplier 01 (anonymized)        Packaging     Beheira                  45         No  Modeled training record - supplier identity an...
1       SUP02  Approved Supplier 02 (anonymized)            Trims  Alexandria                  15        Yes  Modeled training record - supplier identity an...
2       SUP03  Approved Supplier 03 (anonymized)           Fabric     Gharbia                  45         No  Modeled training record - supplier identity an...

======================================================================
WEB_TRAFFIC_DAILY
Date                  object
Sessions               int64
Users                  int64
New_User_Pct         float64
Mobile_Pct           float64
Add_To_Cart_Rate     float64
Checkout_Rate        float64
Orders                 int64
Conversion_Rate      float64
Avg_Page_Load_Sec    float64
Data_Class            object
dtype: object
Missing values:
Series([], dtype: int64)

         Date  Sessions  Users  New_User_Pct  Mobile_Pct  Add_To_Cart_Rate  Checkout_Rate  Orders  Conversion_Rate  Avg_Page_Load_Sec                               Data_Class
0  2023-10-01      1403   1150         0.631       0.782            0.1067         0.0600      43           0.0308               3.27  Modeled digital analytics training data
1  2023-10-02      1150    943         0.624       0.732            0.1069         0.0483      33           0.0295               3.39  Modeled digital analytics training data
2  2023-10-03      1071    878         0.641       0.731            0.1126         0.0483      29           0.0275               2.89  Modeled digital analytics training data

---
## Data Cleaning

In [4]:
# Backup the original dataframes before cleaning
dfs_raw = {name: df.copy() for name, df in dfs.items()}
print(" Raw backup saved")

 Raw backup saved

In [5]:
def clean_dataframe(name, df, verbose=True):

    original_shape = df.shape
    df = df.copy()

    # 1) Normalize column names
    df.columns = (
        df.columns
        .str.strip()
        .str.replace(" ", "_")
        .str.replace("-", "_")
        .str.lower()
    )

    # 2) Drop fully duplicated rows
    dup_count = df.duplicated().sum()
    df = df.drop_duplicates()

    # 3) Clean text columns
    text_cols = df.select_dtypes(include=["object"]).columns
    for col in text_cols:
        df[col] = df[col].astype(str).str.strip()
        df[col] = df[col].replace({"nan": np.nan, "None": np.nan, "": np.nan})

    # 4) Try numeric conversion for numeric-looking columns
    for col in text_cols:
        sample = df[col].dropna().head(100)
        if len(sample) == 0:
            continue
        try:
            converted = pd.to_numeric(sample, errors="raise")
            if converted.notna().mean() > 0.95:
                df[col] = pd.to_numeric(df[col], errors="coerce")
        except (ValueError, TypeError):
            pass

    if verbose:
        print(f"{name:25s} | {original_shape} -> {df.shape} | "
              f"dropped {dup_count} duplicate rows")

    return df

dfs_clean = {name: clean_dataframe(name, df) for name, df in dfs_raw.items()}

business_units            | (5, 5) -> (5, 5) | dropped 0 duplicate rows
case_briefs               | (10, 4) -> (10, 4) | dropped 0 duplicate rows
customer_service          | (6500, 9) -> (6500, 9) | dropped 0 duplicate rows
customers                 | (30000, 9) -> (30000, 9) | dropped 0 duplicate rows
data_dictionary           | (19, 4) -> (19, 4) | dropped 0 duplicate rows
group_operations          | (180, 7) -> (180, 7) | dropped 0 duplicate rows
inventory_history         | (6372, 19) -> (6372, 19) | dropped 0 duplicate rows
locations                 | (5, 9) -> (5, 9) | dropped 0 duplicate rows
machine_downtime          | (2800, 8) -> (2800, 8) | dropped 0 duplicate rows
marketing                 | (420, 15) -> (420, 15) | dropped 0 duplicate rows
materials                 | (12, 6) -> (12, 6) | dropped 0 duplicate rows
printing_batches          | (1900, 15) -> (1900, 15) | dropped 0 duplicate rows
product_bom               | (337, 7) -> (337, 7) | dropped 0 duplicate rows
product_master            | (59, 12) -> (59, 12) | dropped 0 duplicate rows
production_orders         | (2500, 16) -> (2500, 16) | dropped 0 duplicate rows
purchase_orders           | (3600, 13) -> (3600, 13) | dropped 0 duplicate rows
quality                   | (9000, 12) -> (9000, 12) | dropped 0 duplicate rows
sales_transactions        | (180000, 30) -> (180000, 30) | dropped 0 duplicate rows
suppliers                 | (12, 7) -> (12, 7) | dropped 0 duplicate rows
web_traffic_daily         | (1096, 11) -> (1096, 11) | dropped 0 duplicate rows

In [6]:
comparison = pd.DataFrame({
    "before_rows": {n: dfs_raw[n].shape[0] for n in dfs_raw},
    "after_rows":  {n: dfs_clean[n].shape[0] for n in dfs_clean},
    "before_cols": {n: dfs_raw[n].shape[1] for n in dfs_raw},
    "after_cols":  {n: dfs_clean[n].shape[1] for n in dfs_clean},
})
comparison["rows_removed"] = comparison["before_rows"] - comparison["after_rows"]
comparison["cols_added"]   = comparison["after_cols"] - comparison["before_cols"]

print(comparison.to_string())

                    before_rows  after_rows  before_cols  after_cols  rows_removed  cols_added
business_units                5           5            5           5             0           0
case_briefs                  10          10            4           4             0           0
customer_service           6500        6500            9           9             0           0
customers                 30000       30000            9           9             0           0
data_dictionary              19          19            4           4             0           0
group_operations            180         180            7           7             0           0
inventory_history          6372        6372           19          19             0           0
locations                     5           5            9           9             0           0
machine_downtime           2800        2800            8           8             0           0
marketing                   420         420           15          15             0           0
materials                    12          12            6           6             0           0
printing_batches           1900        1900           15          15             0           0
product_bom                 337         337            7           7             0           0
product_master               59          59           12          12             0           0
production_orders          2500        2500           16          16             0           0
purchase_orders            3600        3600           13          13             0           0
quality                    9000        9000           12          12             0           0
sales_transactions       180000      180000           30          30             0           0
suppliers                    12          12            7           7             0           0
web_traffic_daily          1096        1096           11          11             0           0

In [7]:
# Post-cleaning inspection: check dtypes + missing values
for name, df in dfs_clean.items():
    print("=" * 75)
    print(f"📄 {name.upper()}  |  Shape: {df.shape}")
    print("=" * 75)
    print("\ndtypes:")
    print(df.dtypes.to_string())
    print("\nMissing values:")
    miss = df.isna().sum()
    miss = miss[miss > 0].sort_values(ascending=False)
    if len(miss) > 0:
        print(miss.to_string())
    else:
        print("  ✅ No missing values")
    print()

===========================================================================
📄 BUSINESS_UNITS  |  Shape: (5, 5)
===========================================================================

dtypes:
business_unit         object
function              object
public_capacity       object
source_url            object
verification_class    object

Missing values:
  ✅ No missing values

===========================================================================
📄 CASE_BRIEFS  |  Shape: (10, 4)
===========================================================================

dtypes:
card_no                  int64
title                   object
business_problem        object
expected_deliverable    object

Missing values:
  ✅ No missing values

===========================================================================
📄 CUSTOMER_SERVICE  |  Shape: (6500, 9)
===========================================================================

dtypes:
ticket_id                  object
open_date                  object
channel                    object
issue_type                 object
first_response_minutes    float64
resolution_hours          float64
resolved                   object
csat_1_to_5                 int64
data_class                 object

Missing values:
  ✅ No missing values

===========================================================================
📄 CUSTOMERS  |  Shape: (30000, 9)
===========================================================================

dtypes:
customer_id            object
customer_type          object
governorate            object
age_band               object
gender                 object
join_date              object
acquisition_channel    object
consent_status         object
data_class             object

Missing values:
  ✅ No missing values

===========================================================================
📄 DATA_DICTIONARY  |  Shape: (19, 4)
===========================================================================

dtypes:
table              object
grain              object
purpose            object
real_vs_modeled    object

Missing values:
  ✅ No missing values

===========================================================================
📄 GROUP_OPERATIONS  |  Shape: (180, 7)
===========================================================================

dtypes:
month                          object
business_unit                  object
primary_kpi                    object
volume                          int64
operational_efficiency_pct    float64
open_issues_count               int64
data_class                     object

Missing values:
  ✅ No missing values

===========================================================================
📄 INVENTORY_HISTORY  |  Shape: (6372, 19)
===========================================================================

dtypes:
snapshot_month              object
location_id                 object
location_name               object
product_id                  object
sku                         object
product_name                object
opening_stock                int64
received_qty                 int64
sold_qty                     int64
returned_qty                 int64
damaged_qty                  int64
closing_stock                int64
avg_daily_sales_90d        float64
safety_stock_units           int64
reorder_point_units          int64
supplier_lead_time_days      int64
days_of_cover              float64
stockout_days_in_month       int64
data_class                  object

Missing values:
  ✅ No missing values

===========================================================================
📄 LOCATIONS  |  Shape: (5, 9)
===========================================================================

dtypes:
location_id           object
location_name         object
location_type         object
channel               object
governorate           object
city                  object
public_address        object
source_url            object
verification_class    object

Missing values:
  ✅ No missing values

===========================================================================
📄 MACHINE_DOWNTIME  |  Shape: (2800, 8)
===========================================================================

dtypes:
downtime_id        object
date               object
machine_id         object
business_area      object
downtime_hours    float64
reason             object
planned            object
data_class         object

Missing values:
  ✅ No missing values

===========================================================================
📄 MARKETING  |  Shape: (420, 15)
===========================================================================

dtypes:
campaign_id                object
campaign_name              object
product_id                 object
product_name               object
platform                   object
start_date                 object
end_date                   object
spend_egp                   int64
impressions                 int64
clicks                      int64
landing_page_sessions       int64
orders_attributed           int64
attributed_revenue_egp    float64
discount_pct              float64
data_class                 object

Missing values:
  ✅ No missing values

===========================================================================
📄 MATERIALS  |  Shape: (12, 6)
===========================================================================

dtypes:
material_id                object
material_name              object
unit                       object
material_category          object
standard_lead_time_days     int64
data_class                 object

Missing values:
  ✅ No missing values

===========================================================================
📄 PRINTING_BATCHES  |  Shape: (1900, 15)
===========================================================================

dtypes:
print_batch_id                 object
product_id                     object
product_name                   object
print_date                     object
print_type                     object
machine_id                     object
planned_qty                     int64
printed_qty                     int64
good_qty                        int64
rejected_qty                    int64
reprint_qty                     int64
defect_type                    object
ink_or_consumable_cost_egp    float64
rework_cost_egp               float64
data_class                     object

Missing values:
defect_type    381

===========================================================================
📄 PRODUCT_BOM  |  Shape: (337, 7)
===========================================================================

dtypes:
product_id            object
product_name          object
material_id           object
material_name         object
required_per_unit    float64
unit                  object
data_class            object

Missing values:
  ✅ No missing values

===========================================================================
📄 PRODUCT_MASTER  |  Shape: (59, 12)
===========================================================================

dtypes:
product_id                 object
sku                        object
product_name               object
brand                      object
product_family             object
gender                     object
audience                   object
catalog_season             object
sizes                      object
public_retail_price_egp     int64
public_catalog_source      object
verification_class         object

Missing values:
  ✅ No missing values

===========================================================================
📄 PRODUCTION_ORDERS  |  Shape: (2500, 16)
===========================================================================

dtypes:
production_order_id     object
product_id              object
product_name            object
start_date              object
due_date                object
completion_date         object
planned_qty              int64
produced_qty             int64
good_qty                 int64
rejected_qty             int64
line_id                 object
efficiency_pct         float64
delay_days               int64
primary_bottleneck      object
overtime_hours         float64
data_class              object

Missing values:
primary_bottleneck    2093

===========================================================================
📄 PURCHASE_ORDERS  |  Shape: (3600, 13)
===========================================================================

dtypes:
po_id                   object
order_date              object
supplier_id             object
material_id             object
material_name           object
unit                    object
ordered_qty              int64
unit_cost_egp          float64
promised_date           object
actual_receipt_date     object
accepted_qty             int64
rejected_qty             int64
data_class              object

Missing values:
  ✅ No missing values

===========================================================================
📄 QUALITY  |  Shape: (9000, 12)
===========================================================================

dtypes:
qc_id                  object
inspection_date        object
product_id             object
product_name           object
stage                  object
inspected_qty           int64
passed_qty              int64
rejected_qty            int64
defect_type            object
root_cause             object
estimated_loss_egp    float64
data_class             object

Missing values:
defect_type    1972

===========================================================================
📄 SALES_TRANSACTIONS  |  Shape: (180000, 30)
===========================================================================

dtypes:
row_id                      int64
invoice_id                 object
order_date                 object
month_key                  object
location_id                object
location_name              object
channel                    object
customer_id                object
customer_type              object
customer_governorate       object
product_id                 object
sku                        object
product_name               object
product_family             object
size                       object
quantity                    int64
list_price_egp              int64
discount_pct              float64
gross_sales_egp             int64
net_sales_egp             float64
estimated_cogs_egp        float64
gross_profit_egp          float64
gross_margin_pct          float64
payment_method             object
returned                   object
return_date                object
return_reason              object
refund_value_egp          float64
quality_related_return     object
data_class                 object

Missing values:
return_date    171457

===========================================================================
📄 SUPPLIERS  |  Shape: (12, 7)
===========================================================================

dtypes:
supplier_id           object
supplier_name         object
primary_category      object
governorate           object
payment_terms_days     int64
contracted            object
data_class            object

Missing values:
  ✅ No missing values

===========================================================================
📄 WEB_TRAFFIC_DAILY  |  Shape: (1096, 11)
===========================================================================

dtypes:
date                  object
sessions               int64
users                  int64
new_user_pct         float64
mobile_pct           float64
add_to_cart_rate     float64
checkout_rate        float64
orders                 int64
conversion_rate      float64
avg_page_load_sec    float64
data_class            object

Missing values:
  ✅ No missing values

In [8]:
# Summary of missing values across all tables
summary_rows = []
for name, df in dfs_clean.items():
    miss_total = int(df.isna().sum().sum())
    miss_cols = (df.isna().sum() > 0).sum()
    summary_rows.append({
        "table": name,
        "rows": df.shape[0],
        "cols": df.shape[1],
        "missing_total": miss_total,
        "missing_cols": miss_cols,
        "missing_pct": round(miss_total / (df.shape[0] * df.shape[1]) * 100, 2)
    })

missing_summary = pd.DataFrame(summary_rows).sort_values("missing_pct", ascending=False)
print(missing_summary.to_string(index=False))

             table   rows  cols  missing_total  missing_cols  missing_pct
 production_orders   2500    16           2093             1         5.23
sales_transactions 180000    30         171457             1         3.18
           quality   9000    12           1972             1         1.83
  printing_batches   1900    15            381             1         1.34
    business_units      5     5              0             0         0.00
       case_briefs     10     4              0             0         0.00
         suppliers     12     7              0             0         0.00
   purchase_orders   3600    13              0             0         0.00
    product_master     59    12              0             0         0.00
       product_bom    337     7              0             0         0.00
         materials     12     6              0             0         0.00
         marketing    420    15              0             0         0.00
  machine_downtime   2800     8              0             0         0.00
         locations      5     9              0             0         0.00
 inventory_history   6372    19              0             0         0.00
  group_operations    180     7              0             0         0.00
   data_dictionary     19     4              0             0         0.00
         customers  30000     9              0             0         0.00
  customer_service   6500     9              0             0         0.00
 web_traffic_daily   1096    11              0             0         0.00

In [9]:
# Identify which column is missing in each affected table
affected = ["production_orders", "sales_transactions", "quality", "printing_batches"]

for name in affected:
    df = dfs_clean[name]
    miss = df.isna().sum()
    miss = miss[miss > 0]
    print(f"📄 {name}:")
    for col, cnt in miss.items():
        pct = cnt / len(df) * 100
        print(f"   • Column: '{col}'  |  Missing: {cnt:,}  ({pct:.2f}%)")
    print()

📄 production_orders:
   • Column: 'primary_bottleneck'  |  Missing: 2,093  (83.72%)

📄 sales_transactions:
   • Column: 'return_date'  |  Missing: 171,457  (95.25%)

📄 quality:
   • Column: 'defect_type'  |  Missing: 1,972  (21.91%)

📄 printing_batches:
   • Column: 'defect_type'  |  Missing: 381  (20.05%)

In [10]:
# Inspect the dtype and sample of each missing column
for name in affected:
    df = dfs_clean[name]
    miss_cols = df.columns[df.isna().any()].tolist()
    for col in miss_cols:
        print("=" * 70)
        print(f"📄 {name}  |  Column: '{col}'")
        print(f"   dtype: {df[col].dtype}")
        print(f"   nunique (non-null): {df[col].nunique()}")
        print(f"   Sample values (non-null):")
        print(df[col].dropna().head(5).to_string())
        print()

======================================================================
📄 production_orders  |  Column: 'primary_bottleneck'
   dtype: object
   nunique (non-null): 5
   Sample values (non-null):
2     Finishing
5       Packing
6       Packing
13       Sewing
17      Packing

======================================================================
📄 sales_transactions  |  Column: 'return_date'
   dtype: object
   nunique (non-null): 1091
   Sample values (non-null):
7      2024-10-09
37     2023-11-23
40     2024-09-25
74     2026-01-11
108    2024-03-13

======================================================================
📄 quality  |  Column: 'defect_type'
   dtype: object
   nunique (non-null): 8
   Sample values (non-null):
1    Color Misalignment
2        Print Cracking
3         Size Variance
4            Ink Smudge
5         Fabric Defect

======================================================================
📄 printing_batches  |  Column: 'defect_type'
   dtype: object
   nunique (non-null): 5
   Sample values (non-null):
1          Curing
2          Curing
4    Registration
5    Registration
6          Curing

In [11]:
# Inspect the dtype and sample of each missing column
for name in affected:
    df = dfs_clean[name]
    miss_cols = df.columns[df.isna().any()].tolist()
    for col in miss_cols:
        print("=" * 70)
        print(f"📄 {name}  |  Column: '{col}'")
        print(f"   dtype: {df[col].dtype}")
        print(f"   nunique (non-null): {df[col].nunique()}")
        print(f"   Sample values (non-null):")
        print(df[col].dropna().head(5).to_string())
        print()

======================================================================
📄 production_orders  |  Column: 'primary_bottleneck'
   dtype: object
   nunique (non-null): 5
   Sample values (non-null):
2     Finishing
5       Packing
6       Packing
13       Sewing
17      Packing

======================================================================
📄 sales_transactions  |  Column: 'return_date'
   dtype: object
   nunique (non-null): 1091
   Sample values (non-null):
7      2024-10-09
37     2023-11-23
40     2024-09-25
74     2026-01-11
108    2024-03-13

======================================================================
📄 quality  |  Column: 'defect_type'
   dtype: object
   nunique (non-null): 8
   Sample values (non-null):
1    Color Misalignment
2        Print Cracking
3         Size Variance
4            Ink Smudge
5         Fabric Defect

======================================================================
📄 printing_batches  |  Column: 'defect_type'
   dtype: object
   nunique (non-null): 5
   Sample values (non-null):
1          Curing
2          Curing
4    Registration
5    Registration
6          Curing

In [12]:
sales = dfs_clean["sales_transactions"]

In [13]:
# Create binary flag for returns
sales["is_returned"] = sales["return_date"].notna().astype(int)
sales["return_date"] = pd.to_datetime(sales["return_date"], errors="coerce")

# Save back
dfs_clean["sales_transactions"] = sales

print("✅ sales_transactions: created 'is_returned'")
print(f"   Total returns: {sales['is_returned'].sum():,} "
      f"({sales['is_returned'].mean()*100:.2f}%)")

✅ sales_transactions: created 'is_returned'
   Total returns: 8,543 (4.75%)

In [14]:
quality = dfs_clean["quality"]

In [15]:
quality["has_defect"] = quality["defect_type"].notna().astype(int)
dfs_clean["quality"] = quality

print("✅ quality: created 'has_defect'")
print(f"   Defect rate: {quality['has_defect'].mean()*100:.2f}%")

✅ quality: created 'has_defect'
   Defect rate: 78.09%

In [16]:
pb = dfs_clean["printing_batches"]
pb["has_defect"] = pb["defect_type"].notna().astype(int)
dfs_clean["printing_batches"] = pb

print("✅ printing_batches: created 'has_defect'")
print(f"   Defect rate: {pb['has_defect'].mean()*100:.2f}%")

✅ printing_batches: created 'has_defect'
   Defect rate: 79.95%

In [17]:
print(" Verification:\n")

print("sales_transactions - is_returned:")
print(dfs_clean["sales_transactions"]["is_returned"].value_counts().to_string())

print("\nquality - has_defect:")
print(dfs_clean["quality"]["has_defect"].value_counts().to_string())

print("\nprinting_batches - has_defect:")
print(dfs_clean["printing_batches"]["has_defect"].value_counts().to_string())

 Verification:

sales_transactions - is_returned:
is_returned
0    171457
1      8543

quality - has_defect:
has_defect
1    7028
0    1972

printing_batches - has_defect:
has_defect
1    1519
0     381

In [18]:
## Date Convertion

# Auto-detect date-like columns across all tables
print("=" * 75)
print("Date-like columns across all tables")
print("=" * 75)

date_cols_by_table = {}

for name, df in dfs_clean.items():
    date_like = [
        col for col in df.columns
        if "date" in col.lower() or "time" in col.lower() or "timestamp" in col.lower()
    ]
    if date_like:
        date_cols_by_table[name] = date_like
        print(f"\n {name}:")
        for col in date_like:
            print(f"   • {col}  (dtype: {df[col].dtype})")

===========================================================================
Date-like columns across all tables
===========================================================================

 customer_service:
   • open_date  (dtype: object)

 customers:
   • join_date  (dtype: object)

 inventory_history:
   • supplier_lead_time_days  (dtype: int64)

 machine_downtime:
   • downtime_id  (dtype: object)
   • date  (dtype: object)
   • downtime_hours  (dtype: float64)

 marketing:
   • start_date  (dtype: object)
   • end_date  (dtype: object)

 materials:
   • standard_lead_time_days  (dtype: int64)

 printing_batches:
   • print_date  (dtype: object)

 production_orders:
   • start_date  (dtype: object)
   • due_date  (dtype: object)
   • completion_date  (dtype: object)
   • overtime_hours  (dtype: float64)

 purchase_orders:
   • order_date  (dtype: object)
   • promised_date  (dtype: object)
   • actual_receipt_date  (dtype: object)

 quality:
   • inspection_date  (dtype: object)

 sales_transactions:
   • order_date  (dtype: object)
   • return_date  (dtype: datetime64[ns])

 web_traffic_daily:
   • date  (dtype: object)

In [19]:
# Convert all date-like columns to datetime
for name, cols in date_cols_by_table.items():
    df = dfs_clean[name]
    for col in cols:
        df[col] = pd.to_datetime(df[col], errors="coerce")
    dfs_clean[name] = df

print(" All date columns converted to datetime.\n")

# Show new dtypes for confirmation
for name, cols in date_cols_by_table.items():
    print(f" {name}:")
    for col in cols:
        print(f"   • {col}: {dfs_clean[name][col].dtype}")
    print()

C:\Users\abdal\AppData\Local\Temp\ipykernel_10872\3992859428.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors="coerce")

 All date columns converted to datetime.

 customer_service:
   • open_date: datetime64[ns]

 customers:
   • join_date: datetime64[ns]

 inventory_history:
   • supplier_lead_time_days: datetime64[ns]

 machine_downtime:
   • downtime_id: datetime64[ns]
   • date: datetime64[ns]
   • downtime_hours: datetime64[ns]

 marketing:
   • start_date: datetime64[ns]
   • end_date: datetime64[ns]

 materials:
   • standard_lead_time_days: datetime64[ns]

 printing_batches:
   • print_date: datetime64[ns]

 production_orders:
   • start_date: datetime64[ns]
   • due_date: datetime64[ns]
   • completion_date: datetime64[ns]
   • overtime_hours: datetime64[ns]

 purchase_orders:
   • order_date: datetime64[ns]
   • promised_date: datetime64[ns]
   • actual_receipt_date: datetime64[ns]

 quality:
   • inspection_date: datetime64[ns]

 sales_transactions:
   • order_date: datetime64[ns]
   • return_date: datetime64[ns]

 web_traffic_daily:
   • date: datetime64[ns]

In [20]:
# Check for NaT (Not a Time) values after conversion
print(" Verification - NaT check:\n")

for name, cols in date_cols_by_table.items():
    df = dfs_clean[name]
    for col in cols:
        nat_count = df[col].isna().sum()
        if nat_count > 0:
            pct = nat_count / len(df) * 100
            print(f"⚠️  {name}.{col}: {nat_count:,} NaT ({pct:.2f}%)")
        else:
            print(f"✅ {name}.{col}: no NaT")

 Verification - NaT check:

✅ customer_service.open_date: no NaT
✅ customers.join_date: no NaT
✅ inventory_history.supplier_lead_time_days: no NaT
⚠️  machine_downtime.downtime_id: 2,800 NaT (100.00%)
✅ machine_downtime.date: no NaT
✅ machine_downtime.downtime_hours: no NaT
✅ marketing.start_date: no NaT
✅ marketing.end_date: no NaT
✅ materials.standard_lead_time_days: no NaT
✅ printing_batches.print_date: no NaT
✅ production_orders.start_date: no NaT
✅ production_orders.due_date: no NaT
✅ production_orders.completion_date: no NaT
✅ production_orders.overtime_hours: no NaT
✅ purchase_orders.order_date: no NaT
✅ purchase_orders.promised_date: no NaT
✅ purchase_orders.actual_receipt_date: no NaT
✅ quality.inspection_date: no NaT
✅ sales_transactions.order_date: no NaT
⚠️  sales_transactions.return_date: 171,457 NaT (95.25%)
✅ web_traffic_daily.date: no NaT

In [21]:
# Show date ranges for sanity check
print("📅 Date ranges per table:\n")

for name, cols in date_cols_by_table.items():
    df = dfs_clean[name]
    print(f"📄 {name}:")
    for col in cols:
        if df[col].notna().any():
            print(f"   • {col}: {df[col].min()}  →  {df[col].max()}")
    print()

📅 Date ranges per table:

📄 customer_service:
   • open_date: 2023-10-01 00:00:00  →  2026-09-30 00:00:00

📄 customers:
   • join_date: 2023-10-01 00:00:00  →  2026-09-30 00:00:00

📄 inventory_history:
   • supplier_lead_time_days: 1970-01-01 00:00:00.000000005  →  1970-01-01 00:00:00.000000021

📄 machine_downtime:
   • date: 2023-10-02 00:00:00  →  2026-09-30 00:00:00
   • downtime_hours: 1970-01-01 00:00:00  →  1970-01-01 00:00:00.000000014

📄 marketing:
   • start_date: 2023-10-08 00:00:00  →  2026-09-18 00:00:00
   • end_date: 2023-10-22 00:00:00  →  2026-09-30 00:00:00

📄 materials:
   • standard_lead_time_days: 1970-01-01 00:00:00.000000007  →  1970-01-01 00:00:00.000000021

📄 printing_batches:
   • print_date: 2023-10-01 00:00:00  →  2026-09-30 00:00:00

📄 production_orders:
   • start_date: 2023-10-01 00:00:00  →  2026-09-10 00:00:00
   • due_date: 2023-10-09 00:00:00  →  2026-10-01 00:00:00
   • completion_date: 2023-10-09 00:00:00  →  2026-09-30 00:00:00
   • overtime_hours: 1970-01-01 00:00:00  →  1970-01-01 00:00:00.000000033

📄 purchase_orders:
   • order_date: 2023-10-01 00:00:00  →  2026-09-15 00:00:00
   • promised_date: 2023-10-08 00:00:00  →  2026-10-06 00:00:00
   • actual_receipt_date: 2023-10-08 00:00:00  →  2026-09-30 00:00:00

📄 quality:
   • inspection_date: 2023-10-01 00:00:00  →  2026-09-30 00:00:00

📄 sales_transactions:
   • order_date: 2023-10-01 00:00:00  →  2026-09-30 00:00:00
   • return_date: 2023-10-04 00:00:00  →  2026-09-30 00:00:00

📄 web_traffic_daily:
   • date: 2023-10-01 00:00:00  →  2026-09-30 00:00:00

In [22]:
# Fix using column names from dfs_raw (Title Case)
fix_cols = [
    ("inventory_history", "Supplier_Lead_Time_Days",  "supplier_lead_time_days"),
    ("machine_downtime",  "Downtime_Hours",           "downtime_hours"),
    ("materials",         "Standard_Lead_Time_Days",  "standard_lead_time_days"),
    ("production_orders", "Overtime_Hours",           "overtime_hours"),
]

print(" Fixing wrongly-converted columns...\n")

for name, raw_col, clean_col in fix_cols:
    if raw_col in dfs_raw[name].columns and clean_col in dfs_clean[name].columns:
        before_dtype = dfs_clean[name][clean_col].dtype
        # Restore original values from raw, keep clean column name
        dfs_clean[name][clean_col] = dfs_raw[name][raw_col].values
        after_dtype = dfs_clean[name][clean_col].dtype
        print(f"✅ {name}.{clean_col}: {before_dtype} → {after_dtype}")
    else:
        print(f"⚠️  {name}: raw_col='{raw_col}' or clean_col='{clean_col}' NOT FOUND")

print("\n✅ All fixes applied.")

 Fixing wrongly-converted columns...

✅ inventory_history.supplier_lead_time_days: datetime64[ns] → int64
✅ machine_downtime.downtime_hours: datetime64[ns] → float64
✅ materials.standard_lead_time_days: datetime64[ns] → int64
✅ production_orders.overtime_hours: datetime64[ns] → float64

✅ All fixes applied.

In [23]:
print(" Final check on fixed columns:\n")

for name, raw_col, clean_col in fix_cols:
    df = dfs_clean[name]
    sample = df[clean_col].dropna().head(3).tolist()
    n_miss = df[clean_col].isna().sum()
    print(f"{name}.{clean_col:30s} → dtype: {str(df[clean_col].dtype):12s} | "
          f"sample: {sample} | missing: {n_miss}")

 Final check on fixed columns:

inventory_history.supplier_lead_time_days        → dtype: int64        | sample: [5, 21, 21] | missing: 0
machine_downtime.downtime_hours                 → dtype: float64      | sample: [0.7, 0.8, 11.7] | missing: 0
materials.standard_lead_time_days        → dtype: int64        | sample: [10, 14, 10] | missing: 0
production_orders.overtime_hours                 → dtype: float64      | sample: [4.5, 0.5, 14.7] | missing: 0

In [24]:
# Check ALL numeric columns across all tables for suspicious "1970" dates
print("🔍 Scanning for accidentally converted columns (dates around 1970):\n")

suspicious = []
for name, df in dfs_clean.items():
    for col in df.columns:
        if df[col].dtype == "datetime64[ns]":
            # Check if all values are around 1970 (Unix epoch = wrongly converted)
            non_null = df[col].dropna()
            if len(non_null) > 0 and non_null.dt.year.max() <= 1971:
                suspicious.append((name, col, non_null.min(), non_null.max()))

if suspicious:
    print("⚠️  Suspicious columns (likely wrongly converted numbers):\n")
    for name, col, mn, mx in suspicious:
        print(f"  • {name}.{col}: {mn} → {mx}")
else:
    print("✅ No suspicious 1970-era date columns found.")

🔍 Scanning for accidentally converted columns (dates around 1970):

✅ No suspicious 1970-era date columns found.

In [25]:
def add_date_features(df, date_col, prefix=""):
    """
    Extract time-based features from a date column.
    Creates: year, month, quarter, weekday, week_of_year
    """
    df = df.copy()
    p = f"{prefix}_" if prefix else ""
    df[f"{p}year"]         = df[date_col].dt.year
    df[f"{p}month"]        = df[date_col].dt.month
    df[f"{p}quarter"]      = df[date_col].dt.quarter
    df[f"{p}weekday"]      = df[date_col].dt.day_name()
    df[f"{p}week_of_year"] = df[date_col].dt.isocalendar().week.astype("Int64")
    df[f"{p}ym"]           = df[date_col].dt.to_period("M").astype(str)  # "2024-01"
    return df


# ===== sales_transactions =====
sales = dfs_clean["sales_transactions"]
sales = add_date_features(sales, "order_date")
dfs_clean["sales_transactions"] = sales
print("✅ sales_transactions: date features added")

# ===== production_orders =====
po = dfs_clean["production_orders"]
po = add_date_features(po, "start_date")
dfs_clean["production_orders"] = po
print("✅ production_orders: date features added")

# ===== quality =====
q = dfs_clean["quality"]
q = add_date_features(q, "inspection_date")
dfs_clean["quality"] = q
print("✅ quality: date features added")

# ===== purchase_orders =====
purch = dfs_clean["purchase_orders"]
purch = add_date_features(purch, "order_date")
dfs_clean["purchase_orders"] = purch
print("✅ purchase_orders: date features added")

✅ sales_transactions: date features added
✅ production_orders: date features added
✅ quality: date features added
✅ purchase_orders: date features added

In [26]:
print("🔎 Verification - New date features:\n")

for name in ["sales_transactions", "production_orders", "quality", "purchase_orders"]:
    df = dfs_clean[name]
    new_cols = [c for c in df.columns if any(
        c.startswith(p) or f"_{p}" in c 
        for p in ["year", "month", "quarter", "weekday", "week_of_year", "ym"]
    )]
    print(f"📄 {name}:")
    print(f"   Added columns: {new_cols}")
    print(f"   Sample:")
    print(df[new_cols].head(3).to_string())
    print()

🔎 Verification - New date features:

📄 sales_transactions:
   Added columns: ['month_key', 'year', 'month', 'quarter', 'weekday', 'week_of_year', 'ym']
   Sample:
  month_key  year  month  quarter   weekday  week_of_year       ym
0   2024-05  2024      5        2  Saturday            19  2024-05
1   2025-07  2025      7        3  Thursday            31  2025-07
2   2026-05  2026      5        2  Saturday            21  2026-05

📄 production_orders:
   Added columns: ['year', 'month', 'quarter', 'weekday', 'week_of_year', 'ym']
   Sample:
   year  month  quarter   weekday  week_of_year       ym
0  2025     11        4   Tuesday            46  2025-11
1  2025      9        3    Monday            36  2025-09
2  2025      3        1  Saturday            12  2025-03

📄 quality:
   Added columns: ['year', 'month', 'quarter', 'weekday', 'week_of_year', 'ym']
   Sample:
   year  month  quarter    weekday  week_of_year       ym
0  2026      3        1     Monday            11  2026-03
1  2025      9        3     Sunday            38  2025-09
2  2024      8        3  Wednesday            34  2024-08

📄 purchase_orders:
   Added columns: ['year', 'month', 'quarter', 'weekday', 'week_of_year', 'ym']
   Sample:
   year  month  quarter   weekday  week_of_year       ym
0  2025      2        1    Sunday             5  2025-02
1  2025     10        4  Saturday            42  2025-10
2  2024      2        1  Saturday             7  2024-02

In [27]:
# Discover the actual new column names
sales = dfs_clean["sales_transactions"]

# Show all columns that look like date features
date_feature_cols = [c for c in sales.columns if any(
    kw in c.lower() for kw in ["year", "month", "quarter", "weekday", "week"]
)]

print("📋 Actual date feature columns in sales_transactions:")
print(date_feature_cols)
print("\n📋 All columns in sales_transactions:")
print(sales.columns.tolist())

📋 Actual date feature columns in sales_transactions:
['month_key', 'year', 'month', 'quarter', 'weekday', 'week_of_year']

📋 All columns in sales_transactions:
['row_id', 'invoice_id', 'order_date', 'month_key', 'location_id', 'location_name', 'channel', 'customer_id', 'customer_type', 'customer_governorate', 'product_id', 'sku', 'product_name', 'product_family', 'size', 'quantity', 'list_price_egp', 'discount_pct', 'gross_sales_egp', 'net_sales_egp', 'estimated_cogs_egp', 'gross_profit_egp', 'gross_margin_pct', 'payment_method', 'returned', 'return_date', 'return_reason', 'refund_value_egp', 'quality_related_return', 'data_class', 'is_returned', 'year', 'month', 'quarter', 'weekday', 'week_of_year', 'ym']

In [28]:
print("📊 Sales Distribution:\n")

sales = dfs_clean["sales_transactions"]

print("By Year:")
print(sales["year"].value_counts().sort_index().to_string())

print("\nBy Month:")
print(sales["month"].value_counts().sort_index().to_string())

print("\nBy Quarter:")
print(sales["quarter"].value_counts().sort_index().to_string())

print("\nBy Weekday:")
print(sales["weekday"].value_counts().to_string())

print("\nBy Year-Month (ym) — first 15:")
print(sales["ym"].value_counts().sort_index().head(15).to_string())

print(f"\nTotal unique months: {sales['ym'].nunique()}")

📊 Sales Distribution:

By Year:
year
2023    12810
2024    55260
2025    60735
2026    51195

By Month:
month
1     12453
2     11005
3     14573
4     15983
5     17335
6     17274
7     18419
8     17148
9     13612
10    12122
11    13516
12    16560

By Quarter:
quarter
1    38031
2    50592
3    49179
4    42198

By Weekday:
weekday
Sunday       25939
Tuesday      25864
Wednesday    25856
Monday       25784
Thursday     25681
Saturday     25537
Friday       25339

By Year-Month (ym) — first 15:
ym
2023-10    3753
2023-11    4274
2023-12    4783
2024-01    3719
2024-02    3349
2024-03    4251
2024-04    4789
2024-05    5143
2024-06    5073
2024-07    5439
2024-08    4906
2024-09    4044
2024-10    4392
2024-11    4725
2024-12    5430

Total unique months: 36

In [29]:
print("🔎 Comparing 'month_key' vs 'ym':\n")

# Check if they exist
if "month_key" in sales.columns and "ym" in sales.columns:
    sample = sales[["order_date", "month_key", "ym"]].head(10)
    print(sample.to_string())

    same = (sales["month_key"].astype(str) == sales["ym"].astype(str)).all()
    print(f"\n✅ Are they identical? {same}")

    if not same:
        diff = sales[sales["month_key"].astype(str) != sales["ym"].astype(str)]
        print(f"\n⚠️ {len(diff):,} rows differ")
        print(diff[["order_date", "month_key", "ym"]].head(10).to_string())
else:
    print("One of the columns is missing.")

🔎 Comparing 'month_key' vs 'ym':

  order_date month_key       ym
0 2024-05-11   2024-05  2024-05
1 2025-07-31   2025-07  2025-07
2 2026-05-23   2026-05  2026-05
3 2024-06-05   2024-06  2024-06
4 2025-12-28   2025-12  2025-12
5 2025-04-12   2025-04  2025-04
6 2025-03-13   2025-03  2025-03
7 2024-09-18   2024-09  2024-09
8 2025-01-12   2025-01  2025-01
9 2024-11-13   2024-11  2024-11

✅ Are they identical? True

In [30]:
# Remove redundant date feature columns (keep month_key, drop ym)
sales = dfs_clean["sales_transactions"]

if "ym" in sales.columns and "month_key" in sales.columns:
    sales = sales.drop(columns=["ym"])
    print("✅ Dropped 'ym' (kept 'month_key' as the canonical monthly key)")

dfs_clean["sales_transactions"] = sales

✅ Dropped 'ym' (kept 'month_key' as the canonical monthly key)

In [31]:
print("📋 Final columns in sales_transactions:\n")
for i, c in enumerate(sales.columns.tolist(), 1):
    print(f"  {i:2d}. {c}")
print(f"\nTotal: {len(sales.columns)} columns, {len(sales):,} rows")

📋 Final columns in sales_transactions:

   1. row_id
   2. invoice_id
   3. order_date
   4. month_key
   5. location_id
   6. location_name
   7. channel
   8. customer_id
   9. customer_type
  10. customer_governorate
  11. product_id
  12. sku
  13. product_name
  14. product_family
  15. size
  16. quantity
  17. list_price_egp
  18. discount_pct
  19. gross_sales_egp
  20. net_sales_egp
  21. estimated_cogs_egp
  22. gross_profit_egp
  23. gross_margin_pct
  24. payment_method
  25. returned
  26. return_date
  27. return_reason
  28. refund_value_egp
  29. quality_related_return
  30. data_class
  31. is_returned
  32. year
  33. month
  34. quarter
  35. weekday
  36. week_of_year

Total: 36 columns, 180,000 rows

In [32]:
sales = dfs_clean["sales_transactions"]
products = dfs_clean["product_master"]
customers = dfs_clean["customers"]
locations = dfs_clean["locations"]

def check_join(left_df, left_key, right_df, right_key, label):
    left_vals = set(left_df[left_key].dropna().unique())
    right_vals = set(right_df[right_key].dropna().unique())
    common = left_vals & right_vals
    missing = left_vals - right_vals
    pct = len(missing) / len(left_vals) * 100 if left_vals else 0
    status = "✅" if len(missing) == 0 else "⚠️"
    print(f"{status} {label}")
    print(f"   Left: {len(left_vals):,} | Right: {len(right_vals):,} "
          f"| Common: {len(common):,} | Missing: {len(missing):,} ({pct:.2f}%)\n")

check_join(sales, "product_id", products, "product_id", "sales → product_master")
check_join(sales, "customer_id", customers, "customer_id", "sales → customers")
check_join(sales, "location_id", locations, "location_id", "sales → locations")

✅ sales → product_master
   Left: 59 | Right: 59 | Common: 59 | Missing: 0 (0.00%)

✅ sales → customers
   Left: 25,634 | Right: 30,000 | Common: 25,634 | Missing: 0 (0.00%)

✅ sales → locations
   Left: 3 | Right: 5 | Common: 3 | Missing: 0 (0.00%)

In [33]:
sales = dfs_clean["sales_transactions"].copy()
products = dfs_clean["product_master"].copy()
customers = dfs_clean["customers"].copy()
locations = dfs_clean["locations"].copy()

# Join product info
prod_cols = [c for c in products.columns if c not in sales.columns and c != "product_id"]
sales_master = sales.merge(
    products[["product_id"] + prod_cols],
    on="product_id", how="left", suffixes=("", "_prod")
)
print(f"After products: {sales_master.shape}")

# Join customer info
cust_cols = [c for c in customers.columns if c not in sales_master.columns and c != "customer_id"]
sales_master = sales_master.merge(
    customers[["customer_id"] + cust_cols],
    on="customer_id", how="left", suffixes=("", "_cust")
)
print(f"After customers: {sales_master.shape}")

# Join location info
loc_cols = [c for c in locations.columns if c not in sales_master.columns and c != "location_id"]
sales_master = sales_master.merge(
    locations[["location_id"] + loc_cols],
    on="location_id", how="left", suffixes=("", "_loc")
)
print(f"After locations: {sales_master.shape}")

dfs_clean["sales_master"] = sales_master
print(f"\n✅ sales_master created: {sales_master.shape}")

After products: (180000, 44)
After customers: (180000, 49)
After locations: (180000, 53)

✅ sales_master created: (180000, 53)

In [34]:
print("📋 sales_master columns:\n")
for i, c in enumerate(sales_master.columns.tolist(), 1):
    print(f"  {i:2d}. {c}")

print(f"\nShape: {sales_master.shape}")
miss = sales_master.isna().sum()
miss = miss[miss > 0].sort_values(ascending=False)
print(f"\nMissing values (top 10):")
print(miss.head(10).to_string() if len(miss) else "✅ No missing")

📋 sales_master columns:

   1. row_id
   2. invoice_id
   3. order_date
   4. month_key
   5. location_id
   6. location_name
   7. channel
   8. customer_id
   9. customer_type
  10. customer_governorate
  11. product_id
  12. sku
  13. product_name
  14. product_family
  15. size
  16. quantity
  17. list_price_egp
  18. discount_pct
  19. gross_sales_egp
  20. net_sales_egp
  21. estimated_cogs_egp
  22. gross_profit_egp
  23. gross_margin_pct
  24. payment_method
  25. returned
  26. return_date
  27. return_reason
  28. refund_value_egp
  29. quality_related_return
  30. data_class
  31. is_returned
  32. year
  33. month
  34. quarter
  35. weekday
  36. week_of_year
  37. brand
  38. gender
  39. audience
  40. catalog_season
  41. sizes
  42. public_retail_price_egp
  43. public_catalog_source
  44. verification_class
  45. governorate
  46. age_band
  47. join_date
  48. acquisition_channel
  49. consent_status
  50. location_type
  51. city
  52. public_address
  53. source_url

Shape: (180000, 53)

Missing values (top 10):
return_date    171457

In [35]:
key_cols = ["quantity", "gross_sales_egp", "net_sales_egp",
            "estimated_cogs_egp", "gross_profit_egp", "gross_margin_pct"]

print("📊 Numeric summary:\n")
print(sales_master[key_cols].describe().T.to_string())

print("\n📊 Top 10 products by profit:\n")
print(sales_master.groupby("product_name")["gross_profit_egp"]
      .sum().sort_values(ascending=False).head(10).to_string())

print("\n📊 Top 10 governorates by net sales:\n")
print(sales_master.groupby("customer_governorate")["net_sales_egp"]
      .sum().sort_values(ascending=False).head(10).to_string())

📊 Numeric summary:

                       count         mean          std        min       25%       50%        75%       max
quantity            180000.0     9.225494    14.739688     1.0000    1.0000    1.0000    12.0000     60.00
gross_sales_egp     180000.0  3333.844783  5501.195186   289.0000  348.0000  549.0000  3960.0000  32940.00
net_sales_egp       180000.0  2340.768764  3669.395593   216.7500  310.4000  494.1000  2692.8000  23716.80
estimated_cogs_egp  180000.0  1980.278265  3270.571060   155.1100  200.0200  316.8200  2380.1500  21628.41
gross_profit_egp    180000.0   360.490499   566.158340 -1903.7900  107.7200  151.2800   337.4400   6708.04
gross_margin_pct    180000.0     0.291653     0.130789    -0.1417    0.2024    0.3238     0.3897      0.51

📊 Top 10 products by profit:

product_name
Boys' sweatshirt-LEO                     4387022.26
Girls' sweatshirt-Flower                 4020221.18
Summer children's girls-Happy            3074720.98
Ice cream - بيجامة حريمي صيفي2024        2407994.92
Fuchsia - طقم تيشيرت وشورت اطفال صيفي    2165904.54
Summer children's boys-Sonic             1986495.36
Girls' sweatshirt-Fuchsia                1977912.52
BATGIRL - بيجامة حريمي صيفي2024          1950541.80
Girls' summer pajamas-Minnie Mouse       1890119.68
Girls' pajamas-Daylife+kuromi            1652201.45

📊 Top 10 governorates by net sales:

customer_governorate
Alexandria        1.234941e+08
Cairo             7.397313e+07
Giza              4.877389e+07
Beheira           3.513801e+07
Dakahlia          2.780888e+07
Gharbia           2.297662e+07
Sharqia           2.081328e+07
Other             2.062912e+07
Kafr El Sheikh    1.600547e+07
Monufia           1.050683e+07

---
# Scenario 1:
## Product & Profitability Analysis

In [36]:
sales_master = dfs_clean["sales_master"]

# Product-level aggregation
product_summary = (
    sales_master
    .groupby(["product_id", "product_name", "product_family"])
    .agg(
        total_quantity    = ("quantity", "sum"),
        total_net_sales   = ("net_sales_egp", "sum"),
        total_cost        = ("estimated_cogs_egp", "sum"),
        total_profit      = ("gross_profit_egp", "sum"),
        avg_margin_pct    = ("gross_margin_pct", "mean"),
        avg_discount_pct  = ("discount_pct", "mean"),
        n_transactions    = ("invoice_id", "nunique"),
    )
    .reset_index()
)

In [37]:
# Compute profit margin for each product
product_summary["profit_margin_pct"] = (
    product_summary["total_profit"] / product_summary["total_net_sales"] * 100
).round(2)

print(f"📦 Total unique products: {len(product_summary):,}")
print(f"📊 Total profit: {product_summary['total_profit'].sum():,.0f} EGP")
print(f"📊 Total net sales: {product_summary['total_net_sales'].sum():,.0f} EGP")
print(f"\n✅ product_summary created: {product_summary.shape}")

📦 Total unique products: 59
📊 Total profit: 64,888,290 EGP
📊 Total net sales: 421,338,378 EGP

✅ product_summary created: (59, 11)

#### TOP 20 Products by Gross Profit

In [38]:
top20_profit = product_summary.sort_values("total_profit", ascending=False).head(20)

display_cols = ["product_name", "product_family", "total_quantity", 
                "total_net_sales", "total_profit", "profit_margin_pct"]

print(top20_profit[display_cols].to_string(index=False))

                         product_name   product_family  total_quantity  total_net_sales  total_profit  profit_margin_pct
                 Boys' sweatshirt-LEO      Sweatshirts           43038      16587409.14    4387022.26              26.45
             Girls' sweatshirt-Flower      Sweatshirts           59248      22791251.88    4020221.18              17.64
        Summer children's girls-Happy Pajamas/Homewear           68490      16774261.20    3074720.98              18.33
    Ice cream - بيجامة حريمي صيفي2024 Pajamas/Homewear           71864      19595749.88    2407994.92              12.29
Fuchsia - طقم تيشيرت وشورت اطفال صيفي        Kids Sets           26417       7405608.00    2165904.54              29.25
         Summer children's boys-Sonic Pajamas/Homewear           26850       6564957.36    1986495.36              30.26
            Girls' sweatshirt-Fuchsia      Sweatshirts           23838       9165813.03    1977912.52              21.58
      BATGIRL - بيجامة حريمي صيفي2024 Pajamas/Homewear           35480       9661002.12    1950541.80              20.19
   Girls' summer pajamas-Minnie Mouse Pajamas/Homewear           38669       8118747.00    1890119.68              23.28
        Girls' pajamas-Daylife+kuromi Pajamas/Homewear           47288       9810823.85    1652201.45              16.84
    Boys' Autumn Pajamas-Mickey Mouse Pajamas/Homewear           40621       8264475.20    1630530.13              19.73
     Summer children's boys-SpongeBob Pajamas/Homewear           64067      15606338.40    1612066.80              10.33
         Girls' summer pajamas-flower Pajamas/Homewear           33665       7065803.55    1546386.97              21.89
     Boys' summer t-shirt-light beige         T-Shirts           33107       7672919.10    1466018.74              19.11
   Scooby-Doo - بيجامة حريمي صيفي2024 Pajamas/Homewear           31874       8701280.24    1378464.40              15.84
       OHANA - بيجامة حريمي صيفي 2024 Pajamas/Homewear           17351       4729564.80    1371766.93              29.00
       Boys' summer t-shirt-Aubergine         T-Shirts           24833       5769944.40    1300955.14              22.55
     Girls' autumn pajamas-Snow White Pajamas/Homewear           35512       7187273.94    1256008.76              17.48
        Girls' sweatshirt-Tinker Bell      Sweatshirts           17109       6577020.00    1242442.43              18.89
     Boys' sweatshirt-black and white      Sweatshirts           17667       6835620.96    1136439.20              16.63

#### Top 20 by Quantity BUT with Lowest Margin

In [39]:
top_quantity = (
    product_summary
    .sort_values("total_quantity", ascending=False)
    .head(20)
    .sort_values("profit_margin_pct", ascending=True)
)

print(top_quantity[display_cols].to_string(index=False))

                                        product_name   product_family  total_quantity  total_net_sales  total_profit  profit_margin_pct
                 Semon - طقم تيشيرت وشورت اطفال صيفي        Kids Sets           38161      10699100.00      24329.64               0.23
                        Girls' autumn pajamas-Stitch Pajamas/Homewear           37168       7548006.63     229930.09               3.05
                               Boys' sweatshirt-blue      Sweatshirts           37907      14626403.10     961945.23               6.58
              Positive vibes - 2024بيجامة حريمي صيفي Pajamas/Homewear           43208      11779226.04    1082223.69               9.19
                          Boys' summer t-shirt-Black         T-Shirts           40372       9312543.90     923814.83               9.92
             Summer children's boys-Black and orange Pajamas/Homewear           38155       9295939.56     932268.35              10.03
                    Summer children's boys-SpongeBob Pajamas/Homewear           64067      15606338.40    1612066.80              10.33
                     Boys' Autumn Pajamas-Spider Man Pajamas/Homewear           38770       7868773.51     840713.71              10.68
                         Boys' summer pajamas-Mickey Pajamas/Homewear           33684       7095129.47     824612.80              11.62
Summer children's girls-Hello kitty Rose & turquoise Pajamas/Homewear           35481       8674049.64    1013019.56              11.68
                   Ice cream - بيجامة حريمي صيفي2024 Pajamas/Homewear           71864      19595749.88    2407994.92              12.29
                       Girls' pajamas-Daylife+kuromi Pajamas/Homewear           47288       9810823.85    1652201.45              16.84
                    Girls' autumn pajamas-Snow White Pajamas/Homewear           35512       7187273.94    1256008.76              17.48
                            Girls' sweatshirt-Flower      Sweatshirts           59248      22791251.88    4020221.18              17.64
                       Summer children's girls-Happy Pajamas/Homewear           68490      16774261.20    3074720.98              18.33
                   Boys' Autumn Pajamas-Mickey Mouse Pajamas/Homewear           40621       8264475.20    1630530.13              19.73
                     BATGIRL - بيجامة حريمي صيفي2024 Pajamas/Homewear           35480       9661002.12    1950541.80              20.19
                        Girls' summer pajamas-flower Pajamas/Homewear           33665       7065803.55    1546386.97              21.89
                  Girls' summer pajamas-Minnie Mouse Pajamas/Homewear           38669       8118747.00    1890119.68              23.28
                                Boys' sweatshirt-LEO      Sweatshirts           43038      16587409.14    4387022.26              26.45

#### LOSS-MAKING products (negative total profit)

In [40]:
losers = product_summary[product_summary["total_profit"] < 0].sort_values("total_profit")

print(f"Total loss-making products: {len(losers):,} out of {len(product_summary):,}")
print(f"Total loss: {losers['total_profit'].sum():,.0f} EGP\n")

if len(losers) > 0:
    print(losers[display_cols].head(20).to_string(index=False))

Total loss-making products: 1 out of 59
Total loss: -57,780 EGP

              product_name product_family  total_quantity  total_net_sales  total_profit  profit_margin_pct
Boys' summer t-shirt-Beige       T-Shirts           23558        5445125.4     -57780.45              -1.06

#### Family-level performance

In [41]:
print("📊 :\n")

family_summary = (
    sales_master
    .groupby("product_family")
    .agg(
        n_products     = ("product_id", "nunique"),
        total_quantity = ("quantity", "sum"),
        total_net_sales= ("net_sales_egp", "sum"),
        total_profit   = ("gross_profit_egp", "sum"),
    )
    .reset_index()
)
family_summary["profit_margin_pct"] = (
    family_summary["total_profit"] / family_summary["total_net_sales"] * 100
).round(2)
family_summary = family_summary.sort_values("total_profit", ascending=False)

print(family_summary.to_string(index=False))

📊 :

  product_family  n_products  total_quantity  total_net_sales  total_profit  profit_margin_pct
Pajamas/Homewear          42         1176405     272328992.82   41184401.86              15.12
     Sweatshirts           6          198807      76583518.11   13725982.82              17.92
       Kids Sets           5          129980      36453088.00    5274356.82              14.47
        T-Shirts           6          155397      35972778.60    4703548.40              13.08

#### Impact of Discount on Profit

In [42]:
# Bin discount into groups
sales_master["discount_bin"] = pd.cut(
    sales_master["discount_pct"],
    bins=[-0.01, 0, 0.1, 0.2, 0.3, 0.5, 1.0],
    labels=["0%", "0-10%", "10-20%", "20-30%", "30-50%", ">50%"]
)

discount_summary = (
    sales_master
    .groupby("discount_bin", observed=True)
    .agg(
        n_transactions = ("invoice_id", "count"),
        avg_net_sales  = ("net_sales_egp", "mean"),
        avg_profit     = ("gross_profit_egp", "mean"),
        avg_margin_pct = ("gross_margin_pct", "mean"),
    )
    .round(2)
)

print(discount_summary.to_string())

              n_transactions  avg_net_sales  avg_profit  avg_margin_pct
discount_bin
0%                     53862         501.14      203.45            0.41
0-10%                  45270         462.46      164.61            0.35
10-20%                 29908         415.76      117.28            0.28
20-30%                 22882        6644.46     1093.96            0.17
30-50%                 28078        7441.30      638.90            0.08

---
# Scenario 2:
## Customer Segmentation (RFM)

In [43]:
sales_master = dfs_clean["sales_master"]

# Reference date = day after the last order in the dataset
reference_date = sales_master["order_date"].max() + pd.Timedelta(days=1)
print(f"📅 Reference date: {reference_date}")

# RFM calculation per customer
rfm = (
    sales_master
    .groupby("customer_id")
    .agg(
        recency_days   = ("order_date", lambda x: (reference_date - x.max()).days),
        frequency      = ("invoice_id", "nunique"),
        monetary       = ("net_sales_egp", "sum"),
    )
    .reset_index()
)

print(f"\n✅ RFM computed for {len(rfm):,} customers")
print(f"\nSample:")
print(rfm.head(10).to_string(index=False))

print(f"\nDistribution:")
print(rfm[["recency_days", "frequency", "monetary"]].describe().T.to_string())

📅 Reference date: 2026-10-01 00:00:00

✅ RFM computed for 25,634 customers

Sample:
customer_id  recency_days  frequency  monetary
     C00001            25          6   2324.80
     C00002            27          7   2767.25
     C00003            14          4   1355.75
     C00004             1         34 285235.44
     C00005           212          2    515.25
     C00006           109          2    857.50
     C00007           102          1    626.40
     C00008            55          2    549.15
     C00009            54          5   3872.60
     C00010           334          1    388.00

Distribution:
                count          mean           std     min    25%     50%        75%        max
recency_days  25634.0    136.762698    129.018084    1.00   43.0    96.0   187.0000     960.00
frequency     25634.0      7.021924      9.369658    1.00    2.0     4.0     8.0000     120.00
monetary      25634.0  16436.700380  69308.231179  216.75  950.2  2102.5  4114.4625  876177.02

### Score each customer 1-5 on R, F, M

In [44]:

rfm["R_score"] = pd.qcut(rfm["recency_days"], 5, labels=[5, 4, 3, 2, 1]).astype(int)
rfm["F_score"] = pd.qcut(rfm["frequency"].rank(method="first"), 5, labels=[1, 2, 3, 4, 5]).astype(int)
rfm["M_score"] = pd.qcut(rfm["monetary"], 5, labels=[1, 2, 3, 4, 5]).astype(int)

# Combined RFM score
rfm["RFM_score"] = rfm["R_score"].astype(str) + rfm["F_score"].astype(str) + rfm["M_score"].astype(str)

# Weighted total score (simple sum)
rfm["RFM_total"] = rfm["R_score"] + rfm["F_score"] + rfm["M_score"]

print("✅ RFM scores assigned")
print(f"\nSample with scores:")
print(rfm.head(10).to_string(index=False))

✅ RFM scores assigned

Sample with scores:
customer_id  recency_days  frequency  monetary  R_score  F_score  M_score RFM_score  RFM_total
     C00001            25          6   2324.80        5        3        3       533         11
     C00002            27          7   2767.25        5        4        4       544         13
     C00003            14          4   1355.75        5        3        2       532         10
     C00004             1         34 285235.44        5        5        5       555         15
     C00005           212          2    515.25        2        1        1       211          4
     C00006           109          2    857.50        3        1        2       312          6
     C00007           102          1    626.40        3        1        1       311          5
     C00008            55          2    549.15        4        1        1       411          6
     C00009            54          5   3872.60        4        3        4       434         11
     C00010           334          1    388.00        1        1        1       111          3

In [45]:
def segment_customer(row):
    r, f, m = row["R_score"], row["F_score"], row["M_score"]
    
    if r >= 4 and f >= 4 and m >= 4:
        return "Champions"
    elif r >= 4 and f >= 3 and m >= 3:
        return "Loyal"
    elif r >= 4 and f <= 2:
        return "New Customers"
    elif r >= 3 and f >= 2 and m >= 2:
        return "Potential Loyalists"
    elif r <= 2 and f >= 3 and m >= 3:
        return "At Risk"
    elif r <= 2 and f <= 2 and m <= 2:
        return "Lost"
    elif r <= 2 and f >= 4 and m >= 4:
        return "Can't Lose Them"
    else:
        return "Need Attention"

rfm["segment"] = rfm.apply(segment_customer, axis=1)

In [46]:
# Summary
segment_summary = (
    rfm.groupby("segment")
    .agg(
        n_customers   = ("customer_id", "count"),
        total_revenue = ("monetary", "sum"),
        avg_recency   = ("recency_days", "mean"),
        avg_frequency = ("frequency", "mean"),
        avg_monetary  = ("monetary", "mean"),
    )
    .round(2)
    .sort_values("total_revenue", ascending=False)
    .reset_index()
)

segment_summary["revenue_pct"] = (
    segment_summary["total_revenue"] / segment_summary["total_revenue"].sum() * 100
).round(2)
segment_summary["customer_pct"] = (
    segment_summary["n_customers"] / segment_summary["n_customers"].sum() * 100
).round(2)

print("🎯 Customer Segments:\n")
print(segment_summary.to_string(index=False))

dfs_clean["rfm"] = rfm

🎯 Customer Segments:

            segment  n_customers  total_revenue  avg_recency  avg_frequency  avg_monetary  revenue_pct  customer_pct
          Champions         4200   326808243.68        33.78          17.41      77811.49        77.56         16.38
Potential Loyalists         4223    42919806.08        91.37           7.39      10163.35        10.19         16.47
            At Risk         5349    33655263.26       258.28           8.73       6291.88         7.99         20.87
              Loyal         1989     7730690.12        35.99           5.07       3886.72         1.83          7.76
      New Customers         3734     4908595.81        37.09           1.90       1314.57         1.17         14.57
               Lost         4003     2975124.80       259.04           1.76        743.22         0.71         15.62
     Need Attention         2136     2340653.78       163.63           2.21       1095.81         0.56          8.33

In [47]:
print("📊 Segment breakdown — % of customers vs % of revenue:\n")

print(segment_summary[["segment", "n_customers", "customer_pct", 
                       "total_revenue", "revenue_pct", 
                       "avg_monetary", "avg_frequency"]].to_string(index=False))

📊 Segment breakdown — % of customers vs % of revenue:

            segment  n_customers  customer_pct  total_revenue  revenue_pct  avg_monetary  avg_frequency
          Champions         4200         16.38   326808243.68        77.56      77811.49          17.41
Potential Loyalists         4223         16.47    42919806.08        10.19      10163.35           7.39
            At Risk         5349         20.87    33655263.26         7.99       6291.88           8.73
              Loyal         1989          7.76     7730690.12         1.83       3886.72           5.07
      New Customers         3734         14.57     4908595.81         1.17       1314.57           1.90
               Lost         4003         15.62     2975124.80         0.71        743.22           1.76
     Need Attention         2136          8.33     2340653.78         0.56       1095.81           2.21

In [48]:
print(" Average revenue per customer by segment:\n")

segment_summary["revenue_per_customer"] = (
    segment_summary["total_revenue"] / segment_summary["n_customers"]
).round(0)

print(
    segment_summary[["segment", "n_customers", "revenue_per_customer", "avg_frequency"]]
    .sort_values("revenue_per_customer", ascending=False)
    .to_string(index=False)
)

 Average revenue per customer by segment:

            segment  n_customers  revenue_per_customer  avg_frequency
          Champions         4200               77811.0          17.41
Potential Loyalists         4223               10163.0           7.39
            At Risk         5349                6292.0           8.73
              Loyal         1989                3887.0           5.07
      New Customers         3734                1315.0           1.90
     Need Attention         2136                1096.0           2.21
               Lost         4003                 743.0           1.76

In [49]:
print(" One-time buyers analysis:\n")

one_time = rfm[rfm["frequency"] == 1]
repeat = rfm[rfm["frequency"] > 1]

print(f"Total customers: {len(rfm):,}")
print(f"One-time buyers: {len(one_time):,} ({len(one_time)/len(rfm)*100:.2f}%)")
print(f"Repeat buyers:   {len(repeat):,} ({len(repeat)/len(rfm)*100:.2f}%)")

print(f"\nRevenue contribution:")
print(f"  One-time: {one_time['monetary'].sum():,.0f} EGP ({one_time['monetary'].sum()/rfm['monetary'].sum()*100:.2f}%)")
print(f"  Repeat:   {repeat['monetary'].sum():,.0f} EGP ({repeat['monetary'].sum()/rfm['monetary'].sum()*100:.2f}%)")

print(f"\nAverage value per customer:")
print(f"  One-time: {one_time['monetary'].mean():,.0f} EGP")
print(f"  Repeat:   {repeat['monetary'].mean():,.0f} EGP")

 One-time buyers analysis:

Total customers: 25,634
One-time buyers: 4,026 (15.71%)
Repeat buyers:   21,608 (84.29%)

Revenue contribution:
  One-time: 2,306,199 EGP (0.55%)
  Repeat:   419,032,179 EGP (99.45%)

Average value per customer:
  One-time: 573 EGP
  Repeat:   19,392 EGP

---
# Scenario 3:
## Branch & Channel Intelligence

In [50]:
sales_master = dfs_clean["sales_master"]

print(" Available Channels:\n")
print(sales_master["channel"].value_counts().to_string())

print("\n Available Locations:\n")
print(sales_master["location_name"].value_counts().to_string())

print("\n Cross-tab: Channel × Location\n")
print(pd.crosstab(
    sales_master["location_name"],
    sales_master["channel"],
    margins=True
).to_string())

 Available Channels:

channel
Online       71559
Retail       61769
Wholesale    46672

 Available Locations:

location_name
LEO MODA Online Store          71559
LEO MODA - Sidi Bishr Store    61769
El-Sharnouby Wholesale Desk    46672

 Cross-tab: Channel × Location

channel                      Online  Retail  Wholesale     All
location_name
El-Sharnouby Wholesale Desk       0       0      46672   46672
LEO MODA - Sidi Bishr Store       0   61769          0   61769
LEO MODA Online Store         71559       0          0   71559
All                           71559   61769      46672  180000

In [51]:
print(" Channel Performance:\n")

channel_summary = (
    sales_master
    .groupby("channel")
    .agg(
        n_transactions = ("invoice_id", "nunique"),
        n_customers    = ("customer_id", "nunique"),
        total_quantity = ("quantity", "sum"),
        total_net_sales= ("net_sales_egp", "sum"),
        total_profit   = ("gross_profit_egp", "sum"),
        avg_margin     = ("gross_margin_pct", "mean"),
        avg_discount   = ("discount_pct", "mean"),
    )
    .round(2)
    .sort_values("total_net_sales", ascending=False)
    .reset_index()
)

channel_summary["revenue_pct"] = (
    channel_summary["total_net_sales"] / channel_summary["total_net_sales"].sum() * 100
).round(2)
channel_summary["profit_pct"] = (
    channel_summary["total_profit"] / channel_summary["total_profit"].sum() * 100
).round(2)
channel_summary["avg_order_value"] = (
    channel_summary["total_net_sales"] / channel_summary["n_transactions"]
).round(0)

print(channel_summary.to_string(index=False))

 Channel Performance:

  channel  n_transactions  n_customers  total_quantity  total_net_sales  total_profit  avg_margin  avg_discount  revenue_pct  profit_pct  avg_order_value
Wholesale           46672         2754         1475076     359361115.68   42635042.38        0.11          0.33        85.29       65.71           7700.0
   Online           71559        21560           99339      32629574.45   11384070.74        0.34          0.09         7.74       17.54            456.0
   Retail           61769        19472           86174      29347687.40   10869176.78        0.37          0.06         6.97       16.75            475.0

In [52]:
print(" Location Performance:\n")

location_summary = (
    sales_master
    .groupby(["location_id", "location_name"])
    .agg(
        n_transactions = ("invoice_id", "nunique"),
        n_customers    = ("customer_id", "nunique"),
        total_quantity = ("quantity", "sum"),
        total_net_sales= ("net_sales_egp", "sum"),
        total_profit   = ("gross_profit_egp", "sum"),
        avg_margin     = ("gross_margin_pct", "mean"),
    )
    .round(2)
    .sort_values("total_net_sales", ascending=False)
    .reset_index()
)

location_summary["revenue_pct"] = (
    location_summary["total_net_sales"] / location_summary["total_net_sales"].sum() * 100
).round(2)

print(location_summary.to_string(index=False))

 Location Performance:

location_id               location_name  n_transactions  n_customers  total_quantity  total_net_sales  total_profit  avg_margin  revenue_pct
     LOC003 El-Sharnouby Wholesale Desk           46672         2754         1475076     359361115.68   42635042.38        0.11        85.29
     LOC002       LEO MODA Online Store           71559        21560           99339      32629574.45   11384070.74        0.34         7.74
     LOC001 LEO MODA - Sidi Bishr Store           61769        19472           86174      29347687.40   10869176.78        0.37         6.97

In [53]:
print(" Governorate Performance (Top 15):\n")

gov_summary = (
    sales_master
    .groupby("customer_governorate")
    .agg(
        n_customers    = ("customer_id", "nunique"),
        n_transactions = ("invoice_id", "nunique"),
        total_net_sales= ("net_sales_egp", "sum"),
        total_profit   = ("gross_profit_egp", "sum"),
        avg_margin     = ("gross_margin_pct", "mean"),
    )
    .round(2)
    .sort_values("total_net_sales", ascending=False)
    .head(15)
    .reset_index()
)

gov_summary["revenue_pct"] = (
    gov_summary["total_net_sales"] / sales_master["net_sales_egp"].sum() * 100
).round(2)

print(gov_summary.to_string(index=False))

 Governorate Performance (Top 15):

customer_governorate  n_customers  n_transactions  total_net_sales  total_profit  avg_margin  revenue_pct
          Alexandria         7212           51597     123494078.95   18762214.86        0.29        29.31
               Cairo         4631           31864      73973129.41   11442543.37        0.29        17.56
                Giza         2843           20000      48773889.53    7391961.33        0.29        11.58
             Beheira         2031           14628      35138008.29    5343377.00        0.29         8.34
            Dakahlia         1563           11410      27808884.30    4292598.17        0.29         6.60
             Gharbia         1504           10445      22976619.55    3599075.20        0.30         5.45
             Sharqia         1283            8932      20813284.09    3186983.77        0.29         4.94
               Other         1528           10240      20629119.90    3343447.67        0.30         4.90
      Kafr El Sheikh         1034            7240      16005471.02    2514204.32        0.30         3.80
             Monufia          766            4988      10506833.05    1697424.85        0.30         2.49
           Port Said          486            3440       8535237.61    1315217.71        0.29         2.03
            Damietta          507            3440       7583136.45    1249570.97        0.30         1.80
                Suez          246            1776       5100685.38     749670.68        0.28         1.21

In [54]:
print(" Channel × Location — Revenue Matrix:\n")

matrix_revenue = sales_master.pivot_table(
    index="location_name",
    columns="channel",
    values="net_sales_egp",
    aggfunc="sum",
    fill_value=0
).round(0)

print(matrix_revenue.to_string())

print("\n📊 Channel × Location — Profit Margin % Matrix:\n")

matrix_margin = sales_master.pivot_table(
    index="location_name",
    columns="channel",
    values="gross_margin_pct",
    aggfunc="mean",
    fill_value=0
).round(2)

print(matrix_margin.to_string())

 Channel × Location — Revenue Matrix:

channel                          Online      Retail    Wholesale
location_name
El-Sharnouby Wholesale Desk         0.0         0.0  359361116.0
LEO MODA - Sidi Bishr Store         0.0  29347687.0          0.0
LEO MODA Online Store        32629574.0         0.0          0.0

📊 Channel × Location — Profit Margin % Matrix:

channel                      Online  Retail  Wholesale
location_name
El-Sharnouby Wholesale Desk    0.00    0.00       0.11
LEO MODA - Sidi Bishr Store    0.00    0.37       0.00
LEO MODA Online Store          0.34    0.00       0.00

In [55]:
print(" Channel × Customer Type:\n")

channel_customer = pd.crosstab(
    sales_master["channel"],
    sales_master["customer_type"],
    values=sales_master["net_sales_egp"],
    aggfunc="sum",
    margins=True
).round(0)

print(channel_customer.to_string())

print("\n📊 Average Order Value by Channel × Customer Type:\n")

aov_matrix = sales_master.pivot_table(
    index="channel",
    columns="customer_type",
    values="net_sales_egp",
    aggfunc="mean"
).round(0)

print(aov_matrix.to_string())

 Channel × Customer Type:

customer_type      Retail    Wholesale          All
channel
Online         32566566.0      63009.0   32629574.0
Retail         29293020.0      54668.0   29347687.0
Wholesale      15508260.0  343852856.0  359361116.0
All            77367846.0  343970532.0  421338378.0

📊 Average Order Value by Channel × Customer Type:

customer_type  Retail  Wholesale
channel
Online          456.0      496.0
Retail          475.0      502.0
Wholesale      7908.0     7691.0

In [56]:
import os
os.makedirs("powerbi", exist_ok=True)
print("✅ powerbi/ folder created")

✅ powerbi/ folder created

In [57]:
fact_sales = dfs_clean["sales_master"][[
    "row_id", "invoice_id", "order_date", "month_key",
    "location_id", "customer_id", "product_id",
    "quantity", "list_price_egp", "discount_pct",
    "gross_sales_egp", "net_sales_egp", "estimated_cogs_egp",
    "gross_profit_egp", "gross_margin_pct",
    "is_returned", "year", "month", "quarter", "weekday"
]].copy()

fact_sales.to_csv("powerbi/fact_sales.csv", index=False, encoding="utf-8-sig")
print(f"✅ fact_sales: {fact_sales.shape}")

✅ fact_sales: (180000, 20)

In [58]:
dim_product = (
    dfs_clean["sales_master"][["product_id", "product_name", "product_family"]]
    .drop_duplicates(subset=["product_id"])
    .reset_index(drop=True)
)

dim_product.to_csv("powerbi/dim_product.csv", index=False, encoding="utf-8-sig")
print(f"✅ dim_product: {dim_product.shape}")

✅ dim_product: (59, 3)

In [59]:
dim_customer = dfs_clean["customers"].copy()
rfm = dfs_clean["rfm"][["customer_id", "segment", "R_score", "F_score", "M_score"]]
dim_customer = dim_customer.merge(rfm, on="customer_id", how="left")
dim_customer["segment"] = dim_customer["segment"].fillna("No Purchase")

dim_customer.to_csv("powerbi/dim_customer.csv", index=False, encoding="utf-8-sig")
print(f"✅ dim_customer: {dim_customer.shape}")

✅ dim_customer: (30000, 13)

In [60]:
dim_location = dfs_clean["locations"].copy()
dim_location.to_csv("powerbi/dim_location.csv", index=False, encoding="utf-8-sig")
print(f"✅ dim_location: {dim_location.shape}")

✅ dim_location: (5, 9)

In [61]:
date_range = pd.date_range(
    start=dfs_clean["sales_master"]["order_date"].min(),
    end=dfs_clean["sales_master"]["order_date"].max(),
    freq="D"
)

dim_date = pd.DataFrame({
    "date": date_range,
    "year": date_range.year,
    "quarter": date_range.quarter,
    "month": date_range.month,
    "month_name": date_range.strftime("%B"),
    "weekday": date_range.day_name(),
})
dim_date["year_month"] = dim_date["date"].dt.to_period("M").astype(str)

dim_date.to_csv("powerbi/dim_date.csv", index=False, encoding="utf-8-sig")
print(f"✅ dim_date: {dim_date.shape}")

✅ dim_date: (1096, 7)

In [62]:
print("📦 Files ready for Power BI:\n")
for f in sorted(os.listdir("powerbi")):
    size = os.path.getsize(f"powerbi/{f}") / 1024
    print(f"   • {f:25s} ({size:>8.1f} KB)")

📦 Files ready for Power BI:

   • dim_customer.csv          (  4632.6 KB)
   • dim_date.csv              (    47.7 KB)
   • dim_location.csv          (     1.0 KB)
   • dim_product.csv           (     3.4 KB)
   • fact_sales.csv            ( 20819.7 KB)